# A. 데이터 만들기

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(              # df라는 변수에 데이터 프레임을 담아 줍니다.
    {"a": [4, 5, 6, 7,],        # 열 이름을 지정해 주고 시리즈 형태로 데이터를 저장합니다.
     "b": [8, 9, 10, 11],
     "c": [12, 13, 14, 15]},
    index = [1, 2, 3, 4]        # 인덱스는 1, 2, 3, 4로 정해 줍니다.
)

In [4]:
df # 데이터 프레임의 이름을 입력해 출력합니다.

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [6]:
df = pd.DataFrame(
    [[4, 8, 12],
     [5, 9, 13],
     [6, 10, 14],
     [7, 11, 15]],
    index=[1, 2, 3, 4],
    columns=['a', 'b', 'c'] # 열 이름을 따로 정해 줄 수 있습니다.
)
df

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [9]:
df = pd.DataFrame(
    {'a': [4, 5, 6, 7],
     'b': [8, 9, 10, 11],
     'c': [12, 13, 14, 15]},
    index=pd.MultiIndex.from_tuples(                 # 인덱스를 튜플로 지정합니다.
        [('d', 1), ('d', 2), ('e', 1), ('e', 2)],
        names=['n', 'v']                            # 인덱스 이름을 지정합니다.
    )
)
df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

# B. 데이터 정렬하기

In [10]:
df.sort_values('a', ascending=False) # ascending=False를 적어 주면 역순으로 정렬

     a   b   c
n v
e 2  7  11  15
  1  6  10  14
d 2  5   9  13
  1  4   8  12

In [11]:
df.rename(columns={'c':'d'}) # c 열 이름을 d로 변경합니다.

     a   b   d
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [12]:
df.reset_index()

   n  v  a   b   c
0  d  1  4   8  12
1  d  2  5   9  13
2  e  1  6  10  14
3  e  2  7  11  15

In [13]:
df.sort_index()

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [14]:
df.drop(columns=['a', 'b'])

      c
n v
d 1  12
  2  13
e 1  14
  2  15

# C. 행 추출하기

In [15]:
df.head(2) # 2행을 출력합니다.

     a  b   c
n v
d 1  4  8  12
  2  5  9  13

In [16]:
df.tail(2) # 2행을 출력합니다.

     a   b   c
n v
e 1  6  10  14
  2  7  11  15

In [17]:
df[df['a'] > 4] # a열 중 4 보다 큰 값이 있을 경우 해당 행을 추출합니다.

     a   b   c
n v
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

In [22]:
df[df['a'] == 6] # a열 중 6이 있을 경우 해당 행을 추출합니다.

     a   b   c
n v
e 1  6  10  14

In [19]:
df[df['a'] != 5] # a열 중 5가 없을 경우 해당 행을 추출합니다.

     a   b   c
n v
d 1  4   8  12
e 1  6  10  14
  2  7  11  15

In [20]:
df[df['a'].isin([4])] # 원하는 숫자 리스트([int]) 형식으로 써 줍니다.

     a  b   c
n v
d 1  4  8  12

In [51]:
df.sample(frac=0.75) # 실행할 때마다 정해진 비율만큼 랜덤하게 추출합니다.

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 2  7  11  15

In [53]:
df.sample(n=3) # 실행할 때마다 n에서 정한 만큼 랜덤하게 추출합니다.

     a   b   c
n v
d 2  5   9  13
  1  4   8  12
e 1  6  10  14

In [54]:
df.nlargest(3, 'a') # a열에서 큰 순서대로 세 개를 불러옵니다.

     a   b   c
n v
e 2  7  11  15
  1  6  10  14
d 2  5   9  13

In [55]:
df.nsmallest(3, 'a') # a열에서 작은 순서대로 세 개를 불러옵니다.

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14

# D. 열 추출하기

In [56]:
# 0부터 세므로 첫 번째 줄은 인덱스 0, 4번째 줄은 인덱스가 3이 됩니다.
df.iloc[1:4] # [a:b]의 경우, a 인덱스로부터 b-1 인덱스까지 불러오라는 의미입니다.
             # a열에서 순서대로 세 개를 불러옵니다.

     a   b   c
n v
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

In [57]:
df.iloc[2:] # [a:]는 a 인덱스부터 마지막 인덱스까지 불러오라는 의미입니다.

     a   b   c
n v
e 1  6  10  14
  2  7  11  15

In [58]:
df.iloc[:3] # [:b]는 처음부터 b-1 인덱스까지 불러오라는 의미입니다.

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14

In [59]:
df.iloc[:] #[:]는 모든 인덱스를 불러오라는 의미입니다.

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [60]:
df[['a', 'b']] # a열과 b열을 가져오라는 의미입니다.

     a   b
n v
d 1  4   8
  2  5   9
e 1  6  10
  2  7  11

In [61]:
df.filter(regex='c') # 열 이름에 c라는 문자가 포함되어 있으면 출력하라는 의미입니다.

      c
n v
d 1  12
  2  13
e 1  14
  2  15

# E. 행과 열 추출하기

In [62]:
# df.loc[가져올 행, 가져올 열] 형태로 불러옵니다.
df.loc[:, 'a':'c'] # 모든 인덱스에서 a열부터 c열까지 가져오라는 의미입니다.

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [63]:
# 0 인덱스로부터 2 인덱스까지 0번째 열을 가져오라는 의미(첫 열이 0번째)
df.iloc[0:3, [0, 2]]

     a   c
n v
d 1  4  12
  2  5  13
e 1  6  14

In [64]:
# a열 값이 5보다 큰 경우 a열과 c열을 출력하라는 의미입니다.
df.loc[df['a'] > 5, ['a', 'c']]

     a   c
n v
e 1  6  14
  2  7  15

In [65]:
df.iat[1, 2] # 1번째 인덱스에서 2번째 열 값을 가져옵니다.

np.int64(13)

# F. 중복 데이터 다루기

In [66]:
# 실습을 위해 중복된 값이 포함된 데이터 프레임을 만들겠습니다.
df = pd.DataFrame(
    {"a" : [4, 5, 6, 7, 7],
     "b" : [8, 9, 10, 11, 11],
     "c" : [12, 13, 14, 15, 15]},
    index = pd.MultiIndex.from_tuples(
        [('d', 1), ('d', 2), ('e', 1), ('e', 2), ('e', 3)],
        names = ['n', 'v']
    )
)
df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15
  3  7  11  15

In [68]:
df['a'].value_counts()

a
7    2
4    1
5    1
6    1
Name: count, dtype: int64

In [69]:
len(df)

5

In [71]:
df.shape

(5, 3)

In [72]:
df['a'].nunique()

4

In [73]:
df.describe()

             a         b         c
count  5.00000   5.00000   5.00000
mean   5.80000   9.80000  13.80000
std    1.30384   1.30384   1.30384
min    4.00000   8.00000  12.00000
25%    5.00000   9.00000  13.00000
50%    6.00000  10.00000  14.00000
75%    7.00000  11.00000  15.00000
max    7.00000  11.00000  15.00000

In [74]:
df = df.drop_duplicates()
df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

# G. 데이터 파악하기

In [76]:
df.sum()

a    22
b    38
c    54
dtype: int64

In [77]:
df.count()

a    4
b    4
c    4
dtype: int64

In [78]:
df.median()

a     5.5
b     9.5
c    13.5
dtype: float64

In [79]:
df['b'].mean()

np.float64(9.5)

In [80]:
df.quantile([0.25, 0.75])

         a      b      c
0.25  4.75   8.75  12.75
0.75  6.25  10.25  14.25

In [81]:
df.min()

a     4
b     8
c    12
dtype: int64

In [82]:
df.max()

a     7
b    11
c    15
dtype: int64

In [83]:
df.std()

a    1.290994
b    1.290994
c    1.290994
dtype: float64

In [84]:
import numpy as np
df.apply(np.sqrt) # 제곱근 구하기

            a         b         c
n v
d 1  2.000000  2.828427  3.464102
  2  2.236068  3.000000  3.605551
e 1  2.449490  3.162278  3.741657
  2  2.645751  3.316625  3.872983

# H. 결측치 다루기

In [104]:
# 넘파이 라이브러리를 이용해 null 값이 들어 있는 데이터 프레임 만들기

df = pd.DataFrame(
    {'a' : [4, 5, 6, np.nan],
     'b' : [7, 8, np.nan, 9],
     'c' : [10, np.nan, 11, 12]},
    index=pd.MultiIndex.from_tuples(
        [('d', 1), ('d', 2), ('e', 1), ('e', 2)],
        names=['n', 'v']
    )
)
df

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0   NaN
e 1  6.0  NaN  11.0
  2  NaN  9.0  12.0

In [101]:
pd.isnull(df)

         a      b      c
n v
d 1  False  False  False
  2  False  False  False
e 1  False  False  False
  2  False  False  False

In [102]:
pd.notnull(df)

        a     b     c
n v
d 1  True  True  True
  2  True  True  True
e 1  True  True  True
  2  True  True  True

In [103]:
df_notnull = df.dropna()
df_notnull

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [105]:
df_fillna = df.fillna(13) # 13으로 대체하는 예
df_fillna

        a     b     c
n v
d 1   4.0   7.0  10.0
  2   5.0   8.0  13.0
e 1   6.0  13.0  11.0
  2  13.0   9.0  12.0

In [106]:
df_fillna_mean = df.fillna(df['a'].mean()) # a 열의 평균값으로 대체합니다.
df_fillna_mean

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0   5.0
e 1  6.0  5.0  11.0
  2  5.0  9.0  12.0

# I. 새로운 열 만들기

In [107]:
# 새로운 열 만들기 실습을 위한 데이터 프레임 만들기
df = pd.DataFrame(
    {"a" : [4, 5, 6, 7],
     "b" : [8, 9, 10, 11],
     "c" : [12, 13, 14, 15]},
    index = pd.MultiIndex.from_tuples(              # 인덱스를 튜플로 지정합니다.
        [('d', 1), ('d', 2), ('e', 1), ('e', 2)],
        names=['n', 'v']                            # 인덱스 이름을 지정합니다.
    )
)
df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [108]:
df['sum'] = df['a'] + df['b'] + df['c']
df

     a   b   c  sum
n v
d 1  4   8  12   24
  2  5   9  13   27
e 1  6  10  14   30
  2  7  11  15   33

In [109]:
# a열, b열, c열의 값을 모두 곱해 d열을 만들어 줍니다.
df = df.assign(multiply=lambda df: df['a']*df['b']*df['c'])
df

     a   b   c  sum  multiply
n v
d 1  4   8  12   24       384
  2  5   9  13   27       585
e 1  6  10  14   30       840
  2  7  11  15   33      1155

In [110]:
# a열을 두 개로 나누어 각각 새롭게 레이블을 만들라는 의미입니다.
df['qcut'] = pd.qcut(df['a'], 2, labels=["600이하", "600이상"])
df

     a   b   c  sum  multiply   qcut
n v
d 1  4   8  12   24       384  600이하
  2  5   9  13   27       585  600이하
e 1  6  10  14   30       840  600이상
  2  7  11  15   33      1155  600이상

In [113]:
# a열에서 5이하는 모두 5로, 6이상은 모두 6으로 변환합니다.
df['clip'] = df['a'].clip(lower=5, upper=6)
df

     a   b   c  sum  multiply   qcut  clip
n v
d 1  4   8  12   24       384  600이하     5
  2  5   9  13   27       585  600이하     5
e 1  6  10  14   30       840  600이상     6
  2  7  11  15   33      1155  600이상     6

In [114]:
df.max(axis=0) # axis=0은 행과 행 비교, axis=1은 열과 열 비교

a               7
b              11
c              15
sum            33
multiply     1155
qcut        600이상
clip            6
dtype: object

In [116]:
df.min(axis=0) # axis=0은 행과 행 비교, axis=1은 열과 열 비교

a               4
b               8
c              12
sum            24
multiply      384
qcut        600이하
clip            5
dtype: object

# J. 행과 열 변환하기

In [117]:
# 열을 행으로, 행을 열로 변환하기

# 실습을 위해 새로운 데이터를 만듭니다.
df = pd.DataFrame({'A' : {0:'a', 1:'b', 2:'c'},
                   'B' : {0:1, 1:3, 2:5},
                   'C' : {0:2, 1:4, 2:6}})
df

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [118]:
pd.melt(df)

  variable value
0        A     a
1        A     b
2        A     c
3        B     1
4        B     3
5        B     5
6        C     2
7        C     4
8        C     6

In [119]:
pd.melt(df, id_vars=['A'], value_vars=['B']) # A열만 그대로, B열은 행으로 이동

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

In [120]:
# A열만 그대로, B열과 C열은 행으로 이동시킵니다.
df_melt = pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])
df_melt

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
3  a        C      2
4  b        C      4
5  c        C      6

In [121]:

# A열을 새로운 인덱스로 만들고, B열과 C열은 이에 따라 정리합니다.
df_pivot = df_melt.pivot(index='A', columns='variable', values='value')
df_pivot

variable  B  C
A
a         1  2
b         3  4
c         5  6

In [122]:
df_origin = df_pivot.reset_index() # 인덱스를 리셋합니다.
df_origin

variable  A  B  C
0         a  1  2
1         b  3  4
2         c  5  6

In [124]:
df_origin.columns.name = None # 인덱스 열의 이름을 초기화합니다.
df_origin

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

# K. 시리즈 데이터 연결하기

In [125]:
# 시리즈 데이터 만들기
s1 = pd.Series(['a', 'b'])
s1

0    a
1    b
dtype: object

In [126]:
s2 = pd.Series(['c', 'd'])
s2

0    c
1    d
dtype: object

In [127]:
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [128]:
pd.concat([s1, s2], ignore_index=True)

0    a
1    b
2    c
3    d
dtype: object

In [129]:
pd.concat([s1, s2],
          keys=['s1', 's2'],
          names=['Series name', 'Row ID'])

Series name  Row ID
s1           0         a
             1         b
s2           0         c
             1         d
dtype: object

# L. 데이터 프레임 연결하기

In [130]:
# 데이터 프레임 병합 실습을 위한 데이터 프레임 1
df1 = pd.DataFrame([['a', 1],
                    ['b', 2]],
                   columns=['letter', 'number'])
df1

  letter  number
0      a       1
1      b       2

In [131]:
# 데이터 프레임 2
df2 = pd.DataFrame([['c', 3],
                    ['d', 4]],
                    columns=['letter', 'number'])
df2

  letter  number
0      c       3
1      d       4

In [132]:
# 데이터 프레임 3
df3 = pd.DataFrame([['c', 3, 'cat'],
                    ['d', 4, 'dog']],
                   columns=['letter', 'number', 'animal'])
df3

  letter  number animal
0      c       3    cat
1      d       4    dog

In [133]:
# 데이터 프레임 4
df4 = pd.DataFrame([['bird', 'polly'],
                    ['monkey', 'george']],
                   columns=['animal', 'name'])
df4

   animal    name
0    bird   polly
1  monkey  george

In [134]:
pd.concat([df1, df2])

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [136]:
pd.concat([df1, df3])

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [137]:
pd.concat([df1, df3], join="inner")

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [140]:
pd.concat([df1, df4], axis=1)

  letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george

# M. 데이터 병합하기

In [141]:
# 실습을 위한 데이터 프레임 만들기 1
adf = pd.DataFrame({"x1" : ["A", "B", "C"],
                    "x2" : [1, 2, 3]})
adf

  x1  x2
0  A   1
1  B   2
2  C   3

In [150]:
# 데이터 프레임 만들기 2
bdf = pd.DataFrame({"x1" : ["A", "B", "D"],
                    "x3" : ["T", "F", "T"]})
bdf

  x1 x3
0  A  T
1  B  F
2  D  T

In [144]:
# 데이터 프레임 만들기 3
cdf = pd.DataFrame({"x1" : ["B", "C", "D"],
                    "x2": [2, 3, 4]})
cdf

  x1  x2
0  B   2
1  C   3
2  D   4

In [151]:
# x1을 key로 해서, 왼쪽(adf)을 기준으로
# 왼쪽의 adf에는 D가 없으므로 해당 값은 NaN으로 변환합니다.
pd.merge(adf, bdf, how='left', on='x1')

  x1  x2   x3
0  A   1    T
1  B   2    F
2  C   3  NaN

In [152]:
# x1을 키로 해서 병합, 오른쪽(bdf)을 기준으로
# 오른쪽의 bdf에는 C가 없으므로 해당 값은 NaN으로 변환합니다.
pd.merge(adf, bdf, how='right', on='x1')

  x1   x2 x3
0  A  1.0  T
1  B  2.0  F
2  D  NaN  T

In [153]:
pd.merge(adf, bdf, how='inner', on='x1')

  x1  x2 x3
0  A   1  T
1  B   2  F

In [154]:
pd.merge(adf, bdf, how='outer', on='x1')

  x1   x2   x3
0  A  1.0    T
1  B  2.0    F
2  C  3.0  NaN
3  D  NaN    T

In [155]:
# adf와 bdf의 특정한 열을 비교해서 공통 값이 존재하는 경우만 가져옵니다.
# adf.x1열과 bdf.x1열은 A와 B가 같으므로 adf의 해당 값만 출력합니다.
adf[adf.x1.isin(bdf.x1)]

  x1  x2
0  A   1
1  B   2

In [156]:
adf[~adf.x1.isin(bdf.x1)] # 해당 값만 빼고 출력합니다.

  x1  x2
2  C   3

In [157]:
pd.merge(adf, cdf)

  x1  x2
0  B   2
1  C   3

In [158]:
pd.merge(adf, cdf, how='outer')

  x1  x2
0  A   1
1  B   2
2  C   3
3  D   4

In [159]:
pd.merge(adf, cdf, how='outer', indicator=True)

  x1  x2      _merge
0  A   1   left_only
1  B   2        both
2  C   3        both
3  D   4  right_only

In [160]:
pd.merge(adf, cdf, how='outer', indicator=True).query('_merge=="left_only"')

  x1  x2     _merge
0  A   1  left_only

In [161]:
pd.merge(adf, cdf, how='outer', indicator=True).query('_merge=="left_only"').drop(columns=['_merge'])

  x1  x2
0  A   1

# N. 데이터 가공하기

In [162]:
df = pd.DataFrame(
    {"a" : [4, 5, 6, 7],        # 열 이름을 지정해 주고 시리즈 형태로 데이터 저장
     "b" : [8, 9, 10, 11],
     "c" : [12, 13, 14, 15]},
    index=[1, 2, 3, 4]          # 인덱스는 1, 2, 3, 4로 정해줍니다.
)
df

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [163]:
df.shift(1)

     a     b     c
1  NaN   NaN   NaN
2  4.0   8.0  12.0
3  5.0   9.0  13.0
4  6.0  10.0  14.0

In [164]:
df.shift(-1)

     a     b     c
1  5.0   9.0  13.0
2  6.0  10.0  14.0
3  7.0  11.0  15.0
4  NaN   NaN   NaN

In [165]:
df.cumsum()

    a   b   c
1   4   8  12
2   9  17  25
3  15  27  39
4  22  38  54

In [166]:
df.cummax()

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [167]:
df.cummin()

   a  b   c
1  4  8  12
2  4  8  12
3  4  8  12
4  4  8  12

In [168]:
df.cumprod()

     a     b      c
1    4     8     12
2   20    72    156
3  120   720   2184
4  840  7920  32760

# O. 그룹별로 집계하기

In [169]:
# 실습을 위해 데이터를 불러옵니다.
!git clone https://github.com/taehojo/data.git

# 15장의 주택 가격 예측 데이터를 불러옵니다.
df = pd.read_csv("./data/house_train.csv")

Cloning into 'data'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 36 (delta 9), reused 26 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (36/36), 483.12 KiB | 2.09 MiB/s, done.
Resolving deltas: 100% (9/9), done.

In [170]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [171]:
df.groupby(by='YrSold').size() # 팔린 연도를 중심으로 그룹을 만든 후 그룹별 수 표시

YrSold
2006    314
2007    329
2008    304
2009    338
2010    175
dtype: int64

In [172]:
# 팔린 연도를 중심으로 그룹을 만든 후 각 그룹별로 주차장의 넓이를 표시합니다.
df.groupby(by='YrSold')['LotArea'].mean()

YrSold
2006    10489.458599
2007    10863.686930
2008    10587.687500
2009    10294.248521
2010    10220.645714
Name: LotArea, dtype: float64

In [173]:
df['SalePrice'].rank(method='dense') # 각 집 값은 밀집도를 기준으로 몇 번째인가

0       413.0
1       340.0
2       443.0
3       195.0
4       495.0
        ...
1455    315.0
1456    416.0
1457    528.0
1458    200.0
1459    222.0
Name: SalePrice, Length: 1460, dtype: float64

In [174]:
df['SalePrice'].rank(method='min') # 각 집 값이 최저값을 기준으로 몇 번째인가

0       1072.0
1        909.0
2       1135.0
3        490.0
4       1236.0
         ...
1455     828.0
1456    1076.0
1457    1285.0
1458     524.0
1459     591.0
Name: SalePrice, Length: 1460, dtype: float64

In [175]:
# 집 값의 순위를 비율로 표시합니다.(0=가장 싼 집, 1=가장 비싼 집).
df['SalePrice'].rank(pct=True)

0       0.734247
1       0.622603
2       0.777740
3       0.342123
4       0.848973
          ...
1455    0.569863
1456    0.738356
1457    0.880137
1458    0.358904
1459    0.404795
Name: SalePrice, Length: 1460, dtype: float64

In [176]:
# 순위가 같을 때 순서가 빠른 사람을 상위로 처리합니다.
df['SalePrice'].rank(method='first')

0       1072.0
1        909.0
2       1135.0
3        490.0
4       1236.0
         ...
1455     836.0
1456    1080.0
1457    1285.0
1458     524.0
1459     591.0
Name: SalePrice, Length: 1460, dtype: float64